keypress_delay_ms: 20
virtual_modifiers:
  - CapsLock
# key to key
modmap:
  - name: Global
    remap:
      CapsLock: Ctrl_L
      Space:
        held: CapsLock
        alone: Space
      Enter: 
        held: Ctrl_R
        alone: Henkan
      Alt_L: 
        held: Alt_L
        alone: Muhenkan
      Semicolon: Enter
      
# key combination to key combination
keymap:
  - name: Global
    remap:
      Alt-w: Alt-tab
      CapsLock-s: backspace
      CapsLock-i: Up
      CapsLock-j: Left
      CapsLock-k: Down
      CapsLock-l: Right
      Ctrl_L-Enter: Semicolon
      Shift-Enter: Shift-Semicolon
      Ctrl_R-w: KEY_1
      Ctrl_R-e: KEY_2
      Ctrl_R-r: KEY_3
      Ctrl_R-s: KEY_4
      Ctrl_R-d: KEY_5
      Ctrl_R-f: KEY_6
      Ctrl_R-x: KEY_7
      Ctrl_R-c: KEY_8
      Ctrl_R-v: KEY_9
      Ctrl_R-a: KEY_0
      Ctrl_L-CapsLock-j: Home
      Ctrl_L-CapsLock-l: End
      Ctrl_L-KEY_DOT: Ctrl_L-c
